AWSTemplateFormatVersion: '2020-5-27'
Description: >
  This is just a basic ocr app using python and Tesseract.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  OcrFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Ocr:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/ocr
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OcrApi:
    Description: "API Gateway endpoint URL for Prod stage for Ocr function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  OcrFunction:
    Description: "Ocr Lambda Function ARN"
    Value: !GetAtt OcrFunction.Arn
  OcrFunctionIamRole:
    Description: "Implicit IAM Role created for Ocr function"
    Value: !GetAtt OcrFunctionRole.Arn
